"""Transactional LINBO ``.driverpostsync`` publication.

This module owns only the persistent relationship between driver profiles and
LINBO images:

* ``<drivers>/<profile>/image.conf`` stores one image assignment;
* every image aggregates all profiles referencing it;
* ``<images>/<image>/<image>.driverpostsync`` is rendered deterministically;
* an image without profiles receives a cleanup tombstone instead of losing its
  companion file, because an old hook can remain in a LINBO client cache.

The generated shell program implements the existing driver data-plane
contract. It runs inside LINBO after the normal postsync, selects profiles from
client DMI, uses last-known-good payload caches, stages files into the offline
Windows filesystem, and integrates with the persistent Windows SYSTEM startup
task.

No HTTP or FastAPI concepts belong here.  Roots are injectable for tests and
for downstream packaging.
"""

from __future__ import annotations

import os
import stat as stat_module
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterable, Iterator

from linuxmusterTools.common.checks import NameChecker

from .driver_matching import MAX_MATCH_CONF_BYTES, parse_match_conf
from .driver_storage import (
    StorageSecurityError,
    atomic_write,
    file_lock,
    fsync_directory,
    read_bytes_limited,
    require_profile_directory,
    require_regular_file,
    validate_profile_name,
)

LINBO_DIR = Path(os.environ.get("LINBO_DIR", "/srv/linbo"))
DEFAULT_DRIVERS_ROOT = Path(
    os.environ.get("DRIVERS_BASE", str(LINBO_DIR / "drivers"))
)
DEFAULT_IMAGES_ROOT = Path(
    os.environ.get("IMAGE_DIR", str(LINBO_DIR / "images"))
)

MANAGED_HEADER = "# Managed-By: linuxmusterTools.linbo.driver_hooks v1"
LEGACY_GENERATOR_HEADER = "# Generated by LINBO Patchless — DO NOT EDIT MANUALLY"

name_checker = NameChecker()
_MAX_IMAGE_CONF_BYTES = 10 * 1024
_MAX_EXISTING_HOOK_BYTES = 1024 * 1024


class DriverHookError(RuntimeError):
    """Base class for hook publication failures."""


class DriverHookOwnershipError(DriverHookError):
    """An existing hook is not managed by this component."""


class DriverImageAssignedError(DriverHookError):
    """An image lifecycle operation would orphan driver assignments."""

    def __init__(self, image: str, profiles: Iterable[str]) -> None:
        self.image = image
        self.profiles = tuple(_sorted_profiles(profiles))
        super().__init__(
            f"LINBO image {image!r} has assigned driver profiles: "
            + ", ".join(self.profiles)
        )


class DriverAssignmentScanError(DriverHookError):
    """Driver assignments could not be read completely."""

    def __init__(
        self,
        image: str | None,
        failures: Iterable[dict[str, Any]],
    ) -> None:
        self.image = image
        self.failures = tuple(dict(failure) for failure in failures)
        target = f" for image {image!r}" if image is not None else ""
        super().__init__(f"Cannot read driver assignments completely{target}")


class DriverHookTransactionError(DriverHookError):
    """An assignment mutation failed and rollback was attempted."""

    def __init__(
        self,
        message: str,
        *,
        cause: Exception,
        rollback_failures: Iterable[Exception] = (),
    ) -> None:
        super().__init__(message)
        self.cause = cause
        self.rollback_failures = tuple(rollback_failures)


def validate_image_name(name: str) -> str:
    """Validate a native LINBO image basename."""

    if not isinstance(name, str) or not name:
        raise ValueError("Image name must not be empty")
    trimmed = name.strip()
    if trimmed == "." or not name_checker.check_linbo_image_name(trimmed):
        raise ValueError(
            "Image name must contain only [A-Za-z0-9_.-] and must not "
            "contain '..'"
        )
    if len(trimmed) > 100:
        raise ValueError("Image name must be at most 100 characters")
    return trimmed


def _lexical_absolute(path: os.PathLike[str] | str) -> Path:
    """Return an absolute path without following symlinks."""

    return Path(os.path.abspath(os.path.expanduser(os.fspath(path))))


def _read_regular_file(path: Path, max_bytes: int) -> bytes:
    """Adapt the shared bounded reader to the hook byte-only contract."""

    content, _ = read_bytes_limited(path, max_bytes)
    return content


def _image_conf_content(image_name: str) -> str:
    return "# Image assignment for driver profile\n" f"image = {image_name}\n"


def _parse_image_conf(content: str) -> str:
    assignments: list[str] = []
    for line in content.splitlines():
        trimmed = line.strip()
        if not trimmed or trimmed.startswith("#"):
            continue
        key, separator, value = trimmed.partition("=")
        if not separator or key.strip().lower() != "image" or not value.strip():
            raise ValueError("image.conf contains an invalid assignment")
        assignments.append(value.strip())
    if len(assignments) != 1:
        raise ValueError("image.conf must contain exactly one image assignment")
    return assignments[0]


def _sorted_profiles(profiles: Iterable[str]) -> list[str]:
    validated = {validate_profile_name(profile) for profile in profiles}
    return sorted(validated, key=lambda value: (value.casefold(), value))


def render_driverpostsync(image_name: str, profiles: Iterable[str]) -> str:
    """Render the complete native hook or a cleanup tombstone."""

    image = validate_image_name(image_name)
    ordered_profiles = _sorted_profiles(profiles)
    if not ordered_profiles:
        return _TOMBSTONE_TEMPLATE.replace("@@IMAGE@@", image)
    return (
        _FULL_HOOK_TEMPLATE
        .replace("@@IMAGE@@", image)
        .replace("@@PROFILE_COMMENT@@", ", ".join(ordered_profiles))
        .replace("@@PROFILE_LIST@@", " ".join(ordered_profiles))
    )


def _is_managed_hook(content: str, image_name: str) -> bool:
    first_lines = content.splitlines()[:10]
    if MANAGED_HEADER in first_lines:
        return True

    # Permit an in-place migration from the legacy publisher. Both exact
    # legacy headers and the exact image name are required; a generic
    # executable shell file is never treated as owned.
    normal_header = f"# Auto-generated driverpostsync script for image: {image_name}"
    tombstone_header = (
        f"# Auto-generated driverpostsync tombstone for image: {image_name}"
    )
    return (
        LEGACY_GENERATOR_HEADER in first_lines
        and (normal_header in first_lines or tombstone_header in first_lines)
    )


class LinboDriverHookManager:
    """Manage profile assignments and generated image companion hooks."""

    def __init__(
        self,
        *,
        drivers_root: os.PathLike[str] | str = DEFAULT_DRIVERS_ROOT,
        images_root: os.PathLike[str] | str = DEFAULT_IMAGES_ROOT,
        lock_path: os.PathLike[str] | str | None = None,
    ) -> None:
        self.drivers_root = _lexical_absolute(drivers_root)
        self.images_root = _lexical_absolute(images_root)
        self.lock_path = _lexical_absolute(
            lock_path or self.drivers_root / ".driver-profiles.lock"
        )

    @contextmanager
    def _exclusive_lock(self) -> Iterator[None]:
        with file_lock(self.lock_path, create_parent=True):
            yield

    def _profile_content_directory(self, profile_name: str) -> Path:
        profile = validate_profile_name(profile_name)
        try:
            return require_profile_directory(self.drivers_root, profile)
        except FileNotFoundError as error:
            raise FileNotFoundError(f"Driver profile not found: {profile}") from error
        except StorageSecurityError as error:
            raise ValueError(
                f"Driver profile is not a real directory: {profile}"
            ) from error

    def _profile_directory(self, profile_name: str) -> Path:
        profile = validate_profile_name(profile_name)
        directory = self._profile_content_directory(profile)

        match_conf = directory / "match.conf"
        try:
            require_regular_file(match_conf)
        except FileNotFoundError as error:
            raise FileNotFoundError(
                f"Driver profile has no match.conf: {profile}"
            ) from error
        except StorageSecurityError as error:
            raise ValueError(
                f"Driver profile match.conf is not a regular file: {profile}"
            ) from error
        return directory

    def _image_content_directory(self, image_name: str) -> Path:
        image = validate_image_name(image_name)
        directory = self.images_root / image
        try:
            directory_stat = os.lstat(directory)
        except FileNotFoundError as error:
            raise FileNotFoundError(f"LINBO image not found: {image}") from error
        if stat_module.S_ISLNK(directory_stat.st_mode) or not stat_module.S_ISDIR(
            directory_stat.st_mode
        ):
            raise ValueError(f"LINBO image is not a real directory: {image}")
        return directory

    def _image_directory(self, image_name: str) -> Path:
        image = validate_image_name(image_name)
        directory = self._image_content_directory(image)

        image_file = directory / f"{image}.qcow2"
        try:
            image_stat = os.lstat(image_file)
        except FileNotFoundError as error:
            raise FileNotFoundError(
                f"LINBO image directory contains no {image}.qcow2"
            ) from error
        if stat_module.S_ISLNK(image_stat.st_mode) or not stat_module.S_ISREG(
            image_stat.st_mode
        ):
            raise ValueError(f"LINBO image file is not a regular file: {image_file}")
        return directory

    def _require_deployable_profile(self, profile_name: str) -> Path:
        """Require a strict canonical match.conf for client-side deployment.

        The server-side reader accepts the old linuxmuster-tools WIP aliases
        for migration, while the client hook intentionally parses only
        canonical ``vendor``/``product`` keys. Publishing a legacy rule would
        therefore look successful but could never match on a client.
        """

        directory = self._profile_directory(profile_name)
        match_path = directory / "match.conf"
        content = _read_regular_file(match_path, MAX_MATCH_CONF_BYTES).decode(
            "utf-8", errors="strict"
        )
        rule = parse_match_conf(content)
        if rule.schema != "canonical":
            raise ValueError(
                f"Driver profile {profile_name!r} uses legacy match keys; "
                "migrate it to canonical vendor/product keys before assignment"
            )
        return directory

    def _read_optional_image_conf(
        self,
        profile_name: str,
        *,
        require_match: bool = True,
    ) -> tuple[bytes | None, str | None]:
        if require_match:
            directory = self._profile_directory(profile_name)
        else:
            directory = self._profile_content_directory(profile_name)
        image_conf = directory / "image.conf"
        try:
            content = _read_regular_file(image_conf, _MAX_IMAGE_CONF_BYTES)
        except FileNotFoundError:
            return None, None
        return content, _parse_image_conf(content.decode("utf-8", errors="strict"))

    def read_image_conf(self, profile_name: str) -> str | None:
        """Return a validated image assignment or ``None``."""

        _, image = self._read_optional_image_conf(profile_name)
        return validate_image_name(image) if image is not None else None

    def _scan_assignments(self) -> tuple[dict[str, str], list[dict[str, Any]]]:
        assignments: dict[str, str] = {}
        failures: list[dict[str, Any]] = []
        try:
            with os.scandir(self.drivers_root) as directory:
                entries = list(directory)
        except FileNotFoundError:
            return assignments, failures
        except OSError as error:
            return assignments, [
                {
                    "fatal": True,
                    "message": f"Cannot scan driver profiles: {error}",
                }
            ]

        for entry in entries:
            profile: str | None = None
            try:
                if not entry.is_dir(follow_symlinks=False):
                    continue
                profile = validate_profile_name(entry.name)
            except (OSError, ValueError):
                continue

            try:
                previous_content, raw_image = self._read_optional_image_conf(
                    profile,
                    require_match=False,
                )
                if previous_content is None:
                    continue
            except (OSError, UnicodeError, ValueError) as error:
                failures.append(
                    {
                        "fatal": True,
                        "profile": profile,
                        "message": str(error),
                    }
                )
                continue

            try:
                image = validate_image_name(raw_image)
            except (OSError, UnicodeError, ValueError) as error:
                failures.append(
                    {
                        "fatal": True,
                        "profile": profile,
                        "message": str(error),
                    }
                )
                continue

            try:
                self._require_deployable_profile(profile)
                assignments[profile] = image
            except (OSError, UnicodeError, ValueError) as error:
                failures.append(
                    {"profile": profile, "image": image, "message": str(error)}
                )
        return assignments, failures

    @staticmethod
    def _blocking_assignment_failures(
        image_name: str,
        failures: Iterable[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        return [
            failure
            for failure in failures
            if failure.get("fatal") is True or failure.get("image") == image_name
        ]

    def _require_complete_assignments(
        self,
        image_name: str,
        failures: Iterable[dict[str, Any]],
    ) -> None:
        blocking = self._blocking_assignment_failures(image_name, failures)
        if blocking:
            raise DriverAssignmentScanError(image_name, blocking)

    def referencing_profiles(self, image_name: str) -> list[str]:
        """Return all valid profiles assigned to one image."""

        image = validate_image_name(image_name)
        assignments, failures = self._scan_assignments()
        self._require_complete_assignments(image, failures)
        return _sorted_profiles(
            profile for profile, assigned_image in assignments.items()
            if assigned_image == image
        )

    @contextmanager
    def image_content_lifecycle(
        self,
        image_name: str,
        additional_content_roots: Iterable[os.PathLike[str] | str] = (),
        *,
        require_complete: bool = True,
    ) -> Iterator[tuple[Path, ...]]:
        """Serialize image content changes and classify companion hooks.

        Generic image ingestion sets ``require_complete=False`` while it
        atomically publishes or repairs the canonical QCOW2 file. This still
        holds the assignment lock, validates the real image directory and
        protects an existing companion hook. Normal image lifecycle callers
        retain the stricter complete-image requirement.
        """

        image = validate_image_name(image_name)
        with self._exclusive_lock():
            if require_complete:
                image_directory = self._image_directory(image)
            else:
                image_directory = self._image_content_directory(image)
            paths = [image_directory / f"{image}.driverpostsync"]
            for raw_root in additional_content_roots:
                content_root = _lexical_absolute(raw_root)
                try:
                    relative_root = content_root.relative_to(image_directory)
                except ValueError as error:
                    raise ValueError(
                        f"Image content root escapes image directory: {content_root}"
                    ) from error
                current = image_directory
                for component in relative_root.parts:
                    current /= component
                    try:
                        component_stat = os.lstat(current)
                    except FileNotFoundError as error:
                        raise FileNotFoundError(
                            f"Image content root not found: {content_root}"
                        ) from error
                    if stat_module.S_ISLNK(
                        component_stat.st_mode
                    ) or not stat_module.S_ISDIR(component_stat.st_mode):
                        raise DriverHookOwnershipError(
                            "Image content root contains a symlink or non-directory: "
                            f"{current}"
                        )
                paths.extend(self._driverpostsync_paths(content_root))
            unique_paths = tuple(dict.fromkeys(paths))
            yield self._managed_existing_hooks(image, unique_paths)

    @contextmanager
    def unassigned_image_lifecycle(self, image_name: str) -> Iterator[None]:
        """Guard rename/delete operations against stale driver metadata.

        Image lifecycle changes share the assignment lock. Assigned images are
        rejected so no ``image.conf`` can be orphaned. A managed, unassigned
        tombstone is removed before the image operation; an unmanaged
        companion hook remains protected by the normal ownership error.
        """

        image = validate_image_name(image_name)
        with self._exclusive_lock():
            image_directory = self._image_directory(image)
            assignments, failures = self._scan_assignments()
            self._require_complete_assignments(image, failures)
            profiles = {
                profile
                for profile, assigned_image in assignments.items()
                if assigned_image == image
            }
            profiles.update(
                failure["profile"]
                for failure in failures
                if failure.get("image") == image and failure.get("profile")
            )
            if profiles:
                raise DriverImageAssignedError(image, profiles)

            managed_hooks = self._managed_existing_hooks(
                image,
                self._driverpostsync_paths(image_directory),
            )
            snapshots = [
                (
                    hook_path,
                    _read_regular_file(hook_path, _MAX_EXISTING_HOOK_BYTES),
                    os.lstat(hook_path).st_mode & 0o777,
                )
                for hook_path in managed_hooks
            ]
            for hook_path in managed_hooks:
                hook_path.unlink()
            for parent in {path.parent for path in managed_hooks}:
                fsync_directory(parent)

            try:
                yield
            except Exception:
                try:
                    self._image_directory(image)
                except (FileNotFoundError, OSError, ValueError):
                    pass
                else:
                    for hook_path, content, mode in snapshots:
                        atomic_write(hook_path, content, mode)
                raise

    def list_available_images(self) -> list[dict[str, str]]:
        """Return real, complete native QCOW2 base images in stable order.

        An image is available only when a valid directory basename ``name``
        contains a real regular ``name.qcow2`` file.  Symlinked directories or
        image files, incomplete directories, and LINBO housekeeping paths are
        deliberately omitted.
        """

        try:
            with os.scandir(self.images_root) as directory:
                entries = list(directory)
        except FileNotFoundError:
            return []

        images: list[dict[str, str]] = []
        for entry in entries:
            if entry.name in {"tmp", "backups"}:
                continue
            try:
                if not entry.is_dir(follow_symlinks=False):
                    continue
                image = validate_image_name(entry.name)
                self._image_directory(image)
            except (OSError, ValueError):
                continue
            images.append({"name": image, "filename": f"{image}.qcow2"})

        return sorted(
            images,
            key=lambda item: (item["name"].casefold(), item["name"]),
        )

    def _assert_hook_owned(self, hook_path: Path, image_name: str) -> None:
        try:
            hook_stat = os.lstat(hook_path)
        except FileNotFoundError:
            return
        if stat_module.S_ISLNK(hook_stat.st_mode):
            raise DriverHookOwnershipError(
                f"Refusing to replace symlinked driverpostsync hook: {hook_path}"
            )
        if not stat_module.S_ISREG(hook_stat.st_mode):
            raise DriverHookOwnershipError(
                f"Refusing to replace non-file driverpostsync hook: {hook_path}"
            )
        try:
            existing = _read_regular_file(hook_path, _MAX_EXISTING_HOOK_BYTES).decode(
                "utf-8", errors="strict"
            )
        except (OSError, UnicodeError) as error:
            raise DriverHookOwnershipError(
                f"Cannot verify ownership of existing driverpostsync hook: {hook_path}"
            ) from error
        if not _is_managed_hook(existing, image_name):
            raise DriverHookOwnershipError(
                f"Refusing to overwrite unmanaged driverpostsync hook: {hook_path}"
            )

    @staticmethod
    def _driverpostsync_paths(image_directory: Path) -> list[Path]:
        paths: list[Path] = []
        for root, directories, files in os.walk(
            image_directory,
            topdown=True,
            followlinks=False,
        ):
            symlinked_directories = [
                Path(root) / name
                for name in directories
                if os.path.islink(os.path.join(root, name))
            ]
            if symlinked_directories:
                raise DriverHookOwnershipError(
                    "Refusing image lifecycle operation with symlinked "
                    f"directory: {symlinked_directories[0]}"
                )
            paths.extend(
                Path(root) / name
                for name in files
                if name.endswith(".driverpostsync")
            )
        return sorted(paths, key=lambda path: str(path))

    def _managed_existing_hooks(
        self,
        image_name: str,
        hook_paths: Iterable[Path],
    ) -> tuple[Path, ...]:
        managed: list[Path] = []
        for hook_path in hook_paths:
            try:
                os.lstat(hook_path)
            except FileNotFoundError:
                continue
            self._assert_hook_owned(hook_path, image_name)
            managed.append(hook_path)
        return tuple(managed)

    def _regenerate_unlocked(self, image_name: str) -> dict[str, Any]:
        image = validate_image_name(image_name)
        image_directory = self._image_directory(image)
        profiles = self.referencing_profiles(image)
        hook_path = image_directory / f"{image}.driverpostsync"
        self._assert_hook_owned(hook_path, image)
        content = render_driverpostsync(image, profiles)
        atomic_write(hook_path, content, 0o755)
        return {
            "image": image,
            "profiles": profiles,
            "tombstone": not profiles,
            "path": str(hook_path),
        }

    def regenerate_postsync(self, image_name: str) -> dict[str, Any]:
        """Atomically publish the current desired hook for one image."""

        with self._exclusive_lock():
            return self._regenerate_unlocked(image_name)

    @staticmethod
    def _valid_prior_image(raw_image: str | None) -> str | None:
        if raw_image is None:
            return None
        try:
            return validate_image_name(raw_image)
        except ValueError:
            return None

    def _restore_image_conf(
        self,
        profile_name: str,
        previous_content: bytes | None,
    ) -> None:
        directory = self._profile_directory(profile_name)
        target = directory / "image.conf"
        if previous_content is None:
            try:
                target.unlink()
                fsync_directory(directory)
            except FileNotFoundError:
                pass
        else:
            atomic_write(target, previous_content, 0o644)

    def _raise_transaction_failure(
        self,
        *,
        profile_name: str,
        cause: Exception,
        previous_content: bytes | None,
        affected_images: Iterable[str | None],
    ) -> None:
        rollback_failures: list[Exception] = []
        try:
            self._restore_image_conf(profile_name, previous_content)
        except Exception as error:
            rollback_failures.append(error)

        ordered_images = sorted(
            {value for value in affected_images if value is not None},
            key=lambda value: (value.casefold(), value),
        )
        for image in ordered_images:
            try:
                self._regenerate_unlocked(image)
            except Exception as error:
                rollback_failures.append(error)

        raise DriverHookTransactionError(
            f"Driver profile image assignment failed and was rolled back: {profile_name}",
            cause=cause,
            rollback_failures=rollback_failures,
        ) from cause

    def set_profile_image(self, profile_name: str, image_name: str) -> dict[str, str]:
        """Assign a profile to one image and update all affected hooks."""

        profile = validate_profile_name(profile_name)
        image = validate_image_name(image_name)
        with self._exclusive_lock():
            profile_directory = self._require_deployable_profile(profile)
            self._image_directory(image)
            previous_content, raw_previous_image = self._read_optional_image_conf(profile)
            previous_image = self._valid_prior_image(raw_previous_image)
            atomic_write(
                profile_directory / "image.conf", _image_conf_content(image), 0o644
            )
            try:
                self._regenerate_unlocked(image)
                if previous_image is not None and previous_image != image:
                    try:
                        self._regenerate_unlocked(previous_image)
                    except (FileNotFoundError, ValueError):
                        # A removed image or a legacy invalid reference must not
                        # make its image.conf impossible to repair.
                        pass
            except Exception as error:
                self._raise_transaction_failure(
                    profile_name=profile,
                    cause=error,
                    previous_content=previous_content,
                    affected_images=(image, previous_image),
                )
            return {"folder": profile, "image": image}

    def remove_profile_image(self, profile_name: str) -> dict[str, str | None]:
        """Remove one assignment and publish a tombstone when appropriate."""

        profile = validate_profile_name(profile_name)
        with self._exclusive_lock():
            profile_directory = self._profile_directory(profile)
            previous_content, raw_previous_image = self._read_optional_image_conf(profile)
            if previous_content is None:
                return {"folder": profile, "image": None}
            previous_image = self._valid_prior_image(raw_previous_image)
            target = profile_directory / "image.conf"
            target.unlink()
            fsync_directory(profile_directory)
            try:
                if previous_image is not None:
                    try:
                        self._regenerate_unlocked(previous_image)
                    except (FileNotFoundError, ValueError):
                        pass
            except Exception as error:
                self._raise_transaction_failure(
                    profile_name=profile,
                    cause=error,
                    previous_content=previous_content,
                    affected_images=(previous_image,),
                )
            return {"folder": profile, "image": None}

    def reconcile_all_postsync(self) -> dict[str, list[Any]]:
        """Rebuild every valid QCOW2 image hook and report isolated failures."""

        with self._exclusive_lock():
            assignments, failed = self._scan_assignments()
            if any(failure.get("fatal") is True for failure in failed):
                return {"regenerated": [], "failed": failed}
            image_names = set(assignments.values())

            try:
                with os.scandir(self.images_root) as directory:
                    image_entries = list(directory)
            except FileNotFoundError:
                image_entries = []
            except OSError as error:
                image_entries = []
                failed.append({"message": f"Cannot scan LINBO images: {error}"})

            for entry in image_entries:
                try:
                    if not entry.is_dir(follow_symlinks=False):
                        continue
                    image = validate_image_name(entry.name)
                    image_directory = self._image_directory(image)
                    if image in image_names:
                        # An assignment is sufficient reason to publish.  Its
                        # hook ownership is checked once in the regeneration
                        # loop below.
                        continue
                    hook_path = image_directory / f"{image}.driverpostsync"
                    try:
                        os.lstat(hook_path)
                    except FileNotFoundError:
                        # Do not claim every unrelated QCOW2 image by creating
                        # a first tombstone.  Reconcile owns only assigned
                        # images and hooks that it already manages.
                        continue
                    try:
                        self._assert_hook_owned(hook_path, image)
                    except DriverHookOwnershipError as error:
                        failed.append({"image": image, "message": str(error)})
                        continue
                    image_names.add(image)
                except (OSError, ValueError):
                    continue

            regenerated: list[str] = []
            for image in sorted(image_names, key=lambda value: (value.casefold(), value)):
                try:
                    self._regenerate_unlocked(image)
                    regenerated.append(image)
                except Exception as error:
                    failed.append({"image": image, "message": str(error)})

            return {"regenerated": regenerated, "failed": failed}


_FULL_HOOK_TEMPLATE = r"""#!/bin/sh
# Managed-By: linuxmusterTools.linbo.driver_hooks v1
# =============================================================================
# Auto-generated driverpostsync script for image: @@IMAGE@@
# Generated by linuxmuster.net LINBO — DO NOT EDIT MANUALLY
# Profiles: @@PROFILE_COMMENT@@
# =============================================================================

DRIVERPOSTSYNC_RC=0
DRIVERPOSTSYNC_IMAGE="@@IMAGE@@"
DRIVERPOSTSYNC_PROFILES="@@PROFILE_LIST@@"
DRIVERPOSTSYNC_LOG="/tmp/linbo-driverpostsync.log"
DRIVERPOSTSYNC_RSYNC_LOG="/tmp/linbo-driverpostsync-rsync.$$"
DRIVERPOSTSYNC_CACHE="/cache/linbo-driverprofiles/$DRIVERPOSTSYNC_IMAGE"
DRIVERPOSTSYNC_MATCH_CACHE="$DRIVERPOSTSYNC_CACHE/.match"
DRIVERPOSTSYNC_WINDOWS_ROOT="/mnt"
DRIVERPOSTSYNC_TARGET="/mnt/Drivers/LINBO"
DRIVERPOSTSYNC_TASK_FILE="$DRIVERPOSTSYNC_WINDOWS_ROOT/Windows/System32/Tasks/LINBO-Driver-Install"
DRIVERPOSTSYNC_TASK_MARKER="$DRIVERPOSTSYNC_WINDOWS_ROOT/ProgramData/LINBO/Drivers/startup-task-ready"
DRIVERPOSTSYNC_REGISTRY_FILE="/tmp/linbo-driver-install.$$.reg"
DRIVERPOSTSYNC_REGISTRY_LOG="/tmp/linbo-driverpostsync-registry.$$"

echo "=== LINBO Driver Postsync for $DRIVERPOSTSYNC_IMAGE $(date) ===" > "$DRIVERPOSTSYNC_LOG"

if [ ! -d "$DRIVERPOSTSYNC_WINDOWS_ROOT/Windows/System32/config" ] &&
   [ ! -d "$DRIVERPOSTSYNC_WINDOWS_ROOT/WINDOWS/System32/config" ] &&
   [ ! -d "$DRIVERPOSTSYNC_WINDOWS_ROOT/windows/System32/config" ]; then
    echo "Non-Windows target detected; driver integration skipped." | tee -a "$DRIVERPOSTSYNC_LOG"
    cp "$DRIVERPOSTSYNC_LOG" "/cache/linbo-driverpostsync.log" 2>/dev/null
    return 0
fi

if ! mkdir -p "$DRIVERPOSTSYNC_CACHE" "$DRIVERPOSTSYNC_MATCH_CACHE"; then
    echo "Failed to create the driver profile cache." | tee -a "$DRIVERPOSTSYNC_LOG"
    cp "$DRIVERPOSTSYNC_LOG" "/cache/linbo-driverpostsync.log" 2>/dev/null
    return 1
fi

# Read client DMI before downloading any large driver payload. Every assigned
# profile contributes only its tiny match.conf first; the full rsync runs later
# for matching hardware only.
SYS_VENDOR=$(cat /sys/class/dmi/id/sys_vendor 2>/dev/null | tr -d '\n\r' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
PRODUCT_NAME=$(cat /sys/class/dmi/id/product_name 2>/dev/null | tr -d '\n\r' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
echo "DMI: vendor='$SYS_VENDOR' product='$PRODUCT_NAME'" | tee -a "$DRIVERPOSTSYNC_LOG"

MATCHED_FOLDERS=""
rm -f "$DRIVERPOSTSYNC_MATCH_CACHE/.staging-"*.conf

echo "Syncing match metadata for image-assigned profiles..." | tee -a "$DRIVERPOSTSYNC_LOG"
for FOLDER in $DRIVERPOSTSYNC_PROFILES; do
    case "$FOLDER" in
        ""|*[!a-zA-Z0-9._-]*)
            echo "  Skipping invalid profile name: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
            DRIVERPOSTSYNC_RC=1
            continue
            ;;
    esac

    ACTIVE_CONF="$DRIVERPOSTSYNC_MATCH_CACHE/$FOLDER.conf"
    STAGING_CONF="$DRIVERPOSTSYNC_MATCH_CACHE/.staging-$FOLDER-$$.conf"
    rm -f "$STAGING_CONF"

    if rsync -a --timeout=120 "$LINBOSERVER::linbo/drivers/$FOLDER/match.conf" "$STAGING_CONF" > "$DRIVERPOSTSYNC_RSYNC_LOG" 2>&1 &&
       [ -f "$STAGING_CONF" ] && [ -s "$STAGING_CONF" ]; then
        tee -a "$DRIVERPOSTSYNC_LOG" < "$DRIVERPOSTSYNC_RSYNC_LOG"
        if mv "$STAGING_CONF" "$ACTIVE_CONF"; then
            echo "  Synced match metadata: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
        else
            rm -f "$STAGING_CONF"
            echo "  Failed to activate match metadata: $FOLDER; using cached metadata when available" | tee -a "$DRIVERPOSTSYNC_LOG"
            DRIVERPOSTSYNC_RC=1
        fi
    else
        tee -a "$DRIVERPOSTSYNC_LOG" < "$DRIVERPOSTSYNC_RSYNC_LOG"
        rm -f "$STAGING_CONF"
        echo "  Failed to sync match metadata: $FOLDER; using cached metadata when available" | tee -a "$DRIVERPOSTSYNC_LOG"
        DRIVERPOSTSYNC_RC=1
    fi

    CONF="$ACTIVE_CONF"
    [ -f "$CONF" ] || continue

    # Parse match.conf — extract vendor and product lines
    CONF_VENDOR=""
    CONF_PRODUCTS=""
    IN_MATCH=0
    FOUND_MATCH_SECTION=0
    FOUND_VENDOR=0
    FOUND_PRODUCT=0
    INVALID_MATCH_ENTRY=0
    while IFS= read -r line || [ -n "$line" ]; do
        line=$(printf '%s
' "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        case "$line" in
            \#*|\;*|"") continue ;;
            \[*\])
                SECTION_NAME=${line#\[}
                SECTION_NAME=${SECTION_NAME%\]}
                case "$SECTION_NAME" in
                    ""|*[!a-zA-Z0-9_.-]*)
                        INVALID_MATCH_ENTRY=1
                        IN_MATCH=0
                        continue
                        ;;
                esac
                case "$SECTION_NAME" in
                    [mM][aA][tT][cC][hH])
                        if [ "$FOUND_MATCH_SECTION" = "1" ]; then
                            INVALID_MATCH_ENTRY=1
                            IN_MATCH=0
                        else
                            IN_MATCH=1
                            FOUND_MATCH_SECTION=1
                        fi
                        ;;
                    *) IN_MATCH=0 ;;
                esac
                continue
                ;;
            \[*)
                INVALID_MATCH_ENTRY=1
                IN_MATCH=0
                continue
                ;;
        esac
        [ "$IN_MATCH" = "0" ] && continue

        case "$line" in
            *=*) ;;
            *) INVALID_MATCH_ENTRY=1; continue ;;
        esac

        key=$(printf '%s
' "$line" | sed 's/[[:space:]]*=.*//;s/[[:space:]]*$//' | tr '[:upper:]' '[:lower:]')
        value=$(printf '%s
' "$line" | sed 's/^[^=]*=[[:space:]]*//;s/[[:space:]]*$//')

        # Keep the client-side parser as strict as the server-side match.conf
        # validation. A whole-field wildcard is allowed; all other values use
        # the same conservative ASCII character set.
        case "$value" in
            "") INVALID_MATCH_ENTRY=1; continue ;;
            "*") ;;
            *[!a-zA-Z0-9\ .,\(\)/_+#-]*) INVALID_MATCH_ENTRY=1; continue ;;
        esac

        case "$key" in
            vendor)
                if [ "$FOUND_VENDOR" = "1" ]; then
                    INVALID_MATCH_ENTRY=1
                    continue
                fi
                CONF_VENDOR="$value"
                FOUND_VENDOR=1
                ;;
            product)
                CONF_PRODUCTS="$CONF_PRODUCTS|$value"
                FOUND_PRODUCT=1
                ;;
            *) INVALID_MATCH_ENTRY=1 ;;
        esac
    done < "$CONF"

    if [ "$FOUND_MATCH_SECTION" != "1" ] || [ "$FOUND_VENDOR" != "1" ] ||
       [ "$FOUND_PRODUCT" != "1" ] || [ -z "$CONF_VENDOR" ] ||
       [ "$INVALID_MATCH_ENTRY" != "0" ]; then
        echo "  $FOLDER: invalid match.conf (explicit [match], one vendor, and at least one non-empty product are required; use product = * as wildcard), skipping" | tee -a "$DRIVERPOSTSYNC_LOG"
        DRIVERPOSTSYNC_RC=1
        continue
    fi

    # Vendor must either match exactly or be an explicit wildcard. A wildcard
    # vendor does not bypass an explicitly configured product filter.
    if [ "$CONF_VENDOR" != "*" ] && [ "$CONF_VENDOR" != "$SYS_VENDOR" ]; then
        continue
    fi

    # Product substring match. Parse the internal delimiter explicitly. An unquoted "for pat in
    # $CONF_PRODUCTS" would also apply pathname expansion, so product = *
    # could accidentally expand to filenames in the current directory.
    PRODUCTS_LEFT=${CONF_PRODUCTS#|}
    while [ -n "$PRODUCTS_LEFT" ]; do
        case "$PRODUCTS_LEFT" in
            *"|"*)
                pat=${PRODUCTS_LEFT%%|*}
                PRODUCTS_LEFT=${PRODUCTS_LEFT#*|}
                ;;
            *)
                pat=$PRODUCTS_LEFT
                PRODUCTS_LEFT=""
                ;;
        esac
        [ -z "$pat" ] && continue
        if [ "$pat" = "*" ]; then
            echo "  $FOLDER: vendor criteria matched, wildcard product" | tee -a "$DRIVERPOSTSYNC_LOG"
            MATCHED_FOLDERS="$MATCHED_FOLDERS $FOLDER"
            break
        fi
        case "$PRODUCT_NAME" in
            *"$pat"*)
                echo "  $FOLDER: matched (product contains '$pat')" | tee -a "$DRIVERPOSTSYNC_LOG"
                MATCHED_FOLDERS="$MATCHED_FOLDERS $FOLDER"
                break
                ;;
        esac
    done
done

# Drop cached match files for profiles that are no longer assigned to this
# image. The full payload cache is pruned against MATCHED_FOLDERS below.
for CACHED_CONF in "$DRIVERPOSTSYNC_MATCH_CACHE"/*.conf; do
    [ -f "$CACHED_CONF" ] || continue
    CACHED_FILE=$(basename "$CACHED_CONF")
    CACHED_NAME=$(printf '%s
' "$CACHED_FILE" | sed 's/\.conf$//')
    KEEP=0
    for FOLDER in $DRIVERPOSTSYNC_PROFILES; do
        [ "$CACHED_NAME" = "$FOLDER" ] && KEEP=1 && break
    done
    [ "$KEEP" = "1" ] || rm -f "$CACHED_CONF"
done
rm -f "$DRIVERPOSTSYNC_RSYNC_LOG"

echo "Matched folders: $MATCHED_FOLDERS" | tee -a "$DRIVERPOSTSYNC_LOG"

echo "Syncing full payload for matched profiles only..." | tee -a "$DRIVERPOSTSYNC_LOG"
for FOLDER in $MATCHED_FOLDERS; do
    ACTIVE_PROFILE="$DRIVERPOSTSYNC_CACHE/$FOLDER"
    STAGING_PROFILE="$DRIVERPOSTSYNC_CACHE/.staging-$FOLDER-$$"
    PREVIOUS_PROFILE="$DRIVERPOSTSYNC_CACHE/.previous-$FOLDER-$$"

    # Recover a last-known-good cache if a prior client run was interrupted
    # between the two atomic renames. Stale staging trees are never consumed.
    for CRASH_BACKUP in "$DRIVERPOSTSYNC_CACHE/.previous-$FOLDER-"*; do
        [ -d "$CRASH_BACKUP" ] || continue
        if [ ! -d "$ACTIVE_PROFILE" ]; then
            if mv "$CRASH_BACKUP" "$ACTIVE_PROFILE"; then
                echo "  Recovered last-known-good cache: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
            else
                echo "  Failed to recover cached profile: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
                DRIVERPOSTSYNC_RC=1
            fi
        else
            rm -rf "$CRASH_BACKUP"
        fi
    done
    rm -rf "$DRIVERPOSTSYNC_CACHE/.staging-$FOLDER-"* "$STAGING_PROFILE" "$PREVIOUS_PROFILE"

    if ! mkdir -p "$STAGING_PROFILE"; then
        echo "  Failed to create staging cache: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
        DRIVERPOSTSYNC_RC=1
        continue
    fi

    if rsync -a --delete --timeout=120 "$LINBOSERVER::linbo/drivers/$FOLDER/" "$STAGING_PROFILE/" > "$DRIVERPOSTSYNC_RSYNC_LOG" 2>&1; then
        tee -a "$DRIVERPOSTSYNC_LOG" < "$DRIVERPOSTSYNC_RSYNC_LOG"
        SWAP_OK=1
        if [ -d "$ACTIVE_PROFILE" ] && ! mv "$ACTIVE_PROFILE" "$PREVIOUS_PROFILE"; then
            echo "  Failed to stage previous cache: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
            SWAP_OK=0
        fi
        if [ "$SWAP_OK" = "1" ] && mv "$STAGING_PROFILE" "$ACTIVE_PROFILE"; then
            rm -rf "$PREVIOUS_PROFILE"
            echo "  Synced matched profile: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
        else
            rm -rf "$STAGING_PROFILE"
            if [ -d "$PREVIOUS_PROFILE" ] && [ ! -d "$ACTIVE_PROFILE" ]; then
                if ! mv "$PREVIOUS_PROFILE" "$ACTIVE_PROFILE"; then
                    echo "  Failed to restore last-known-good cache: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
                fi
            fi
            echo "  Failed to activate synced profile: $FOLDER; keeping last-known-good cache" | tee -a "$DRIVERPOSTSYNC_LOG"
            DRIVERPOSTSYNC_RC=1
        fi
    else
        tee -a "$DRIVERPOSTSYNC_LOG" < "$DRIVERPOSTSYNC_RSYNC_LOG"
        rm -rf "$STAGING_PROFILE"
        echo "  Failed to sync matched profile: $FOLDER; keeping last-known-good cache" | tee -a "$DRIVERPOSTSYNC_LOG"
        DRIVERPOSTSYNC_RC=1
    fi
done
rm -f "$DRIVERPOSTSYNC_RSYNC_LOG"

# Retain full payloads for this client's current hardware matches only.
for CACHED_DIR in "$DRIVERPOSTSYNC_CACHE"/*; do
    [ -d "$CACHED_DIR" ] || continue
    CACHED_NAME=$(basename "$CACHED_DIR")
    KEEP=0
    for FOLDER in $MATCHED_FOLDERS; do
        [ "$CACHED_NAME" = "$FOLDER" ] && KEEP=1 && break
    done
    [ "$KEEP" = "1" ] || rm -rf "$CACHED_DIR"
done

# Recreate the managed driver target to avoid stale driver files.
DRIVERPOSTSYNC_INSTALL_READY=1
if ! rm -rf "$DRIVERPOSTSYNC_TARGET"; then
    echo "Failed to clear managed Windows driver target; installation disabled." | tee -a "$DRIVERPOSTSYNC_LOG"
    DRIVERPOSTSYNC_INSTALL_READY=0
    DRIVERPOSTSYNC_RC=1
elif ! mkdir -p "$DRIVERPOSTSYNC_TARGET"; then
    echo "Failed to create managed Windows driver target; installation disabled." | tee -a "$DRIVERPOSTSYNC_LOG"
    DRIVERPOSTSYNC_INSTALL_READY=0
    DRIVERPOSTSYNC_RC=1
fi

# Copy matched driver folders to Windows target
if [ "$DRIVERPOSTSYNC_INSTALL_READY" = "1" ]; then
    for FOLDER in $MATCHED_FOLDERS; do
        SRC="$DRIVERPOSTSYNC_CACHE/$FOLDER"
        if [ -d "$SRC" ]; then
            FILE_COUNT=$(find "$SRC" -type f ! -name "match.conf" ! -name "image.conf" ! -name "driver-map.json" ! -name "driver-manifest.json" ! -name ".extracting" 2>/dev/null | wc -l)
            if [ "$FILE_COUNT" -gt 0 ]; then
                echo "  Copying drivers from: $FOLDER ($FILE_COUNT files)" | tee -a "$DRIVERPOSTSYNC_LOG"
                DEST="$DRIVERPOSTSYNC_TARGET/$FOLDER"
                if mkdir -p "$DEST" &&
                   cp -R "$SRC/." "$DEST/" &&
                   rm -f "$DEST/match.conf" "$DEST/image.conf" "$DEST/driver-map.json" "$DEST/driver-manifest.json" "$DEST/.extracting"; then
                    echo "  Copied driver payload: $FOLDER" | tee -a "$DRIVERPOSTSYNC_LOG"
                else
                    echo "  Failed to copy driver payload: $FOLDER; installation disabled" | tee -a "$DRIVERPOSTSYNC_LOG"
                    rm -rf "$DEST"
                    DRIVERPOSTSYNC_INSTALL_READY=0
                    DRIVERPOSTSYNC_RC=1
                    break
                fi
            else
                echo "  $FOLDER: no driver files, skipping copy" | tee -a "$DRIVERPOSTSYNC_LOG"
            fi
        fi
    done
fi

if [ "$DRIVERPOSTSYNC_INSTALL_READY" != "1" ]; then
    if ! rm -f "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd"; then
        echo "Warning: could not remove stale pnputil-install.cmd." | tee -a "$DRIVERPOSTSYNC_LOG"
    fi
fi

# Build a retryable installer only after the complete payload is ready.
INF_COUNT=0
if [ "$DRIVERPOSTSYNC_INSTALL_READY" = "1" ]; then
    INF_COUNT=$(find "$DRIVERPOSTSYNC_TARGET" -iname '*.inf' 2>/dev/null | wc -l)
fi

DRIVERPOSTSYNC_BATCH_READY=0
if [ "$INF_COUNT" -gt 0 ]; then
    if printf '@echo off\r\n' > "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'setlocal EnableExtensions\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'set "LINBO_LOG_DIR=%%ProgramData%%\\LINBO\\Drivers"\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'if not exist "%%LINBO_LOG_DIR%%" mkdir "%%LINBO_LOG_DIR%%"\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'set "LINBO_LOG=%%LINBO_LOG_DIR%%\\driver-install.log"\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf '>>"%%LINBO_LOG%%" echo [%%DATE%% %%TIME%%] Starting LINBO driver installation.\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf '"%%SystemRoot%%\\System32\\pnputil.exe" /add-driver C:\\Drivers\\LINBO\\*.inf /subdirs /install >>"%%LINBO_LOG%%" 2>&1\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'set "LINBO_RC=%%ERRORLEVEL%%"\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'if "%%LINBO_RC%%"=="0" goto success\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'if "%%LINBO_RC%%"=="259" goto no_action\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'if "%%LINBO_RC%%"=="1641" goto success\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'if "%%LINBO_RC%%"=="3010" goto success\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf '>>"%%LINBO_LOG%%" echo [%%DATE%% %%TIME%%] pnputil failed with exit code %%LINBO_RC%%; installer retained for retry.\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'exit /b %%LINBO_RC%%\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf ':no_action\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf '>>"%%LINBO_LOG%%" echo [%%DATE%% %%TIME%%] pnputil completed with exit code 259: no matching device or a better/newer driver is already active.\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'goto cleanup\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf ':success\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf '>>"%%LINBO_LOG%%" echo [%%DATE%% %%TIME%%] Driver installation succeeded with exit code %%LINBO_RC%%.\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf ':cleanup\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'del "%%~f0" >>"%%LINBO_LOG%%" 2>&1\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'if exist "%%~f0" exit /b 1\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd" &&
       printf 'exit /b 0\r\n' >> "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd"; then
        DRIVERPOSTSYNC_BATCH_READY=1
    else
        echo "Failed to create pnputil-install.cmd; installation disabled." | tee -a "$DRIVERPOSTSYNC_LOG"
        rm -f "$DRIVERPOSTSYNC_TARGET/pnputil-install.cmd"
        DRIVERPOSTSYNC_INSTALL_READY=0
        DRIVERPOSTSYNC_RC=1
    fi
fi

DRIVERPOSTSYNC_TASK_READY=0
# Prefer the canonical native task. Task and marker are checked as a pair so a
# partial migration can never be mistaken for a ready SYSTEM installation.
for WINDOWS_DIR in Windows WINDOWS windows; do
    TASK_CANDIDATE="$DRIVERPOSTSYNC_WINDOWS_ROOT/$WINDOWS_DIR/System32/Tasks/LINBO-Driver-Install"
    [ -f "$TASK_CANDIDATE" ] || continue
    for PROGRAMDATA_DIR in ProgramData PROGRAMDATA programdata; do
        MARKER_CANDIDATE="$DRIVERPOSTSYNC_WINDOWS_ROOT/$PROGRAMDATA_DIR/LINBO/Drivers/startup-task-ready"
        if [ -f "$MARKER_CANDIDATE" ] &&
           [ "$(cat "$MARKER_CANDIDATE" 2>/dev/null)" = "LINBO SYSTEM driver startup task v1" ]; then
            DRIVERPOSTSYNC_TASK_FILE="$TASK_CANDIDATE"
            DRIVERPOSTSYNC_TASK_MARKER="$MARKER_CANDIDATE"
            DRIVERPOSTSYNC_TASK_READY=1
            break
        fi
    done
    [ "$DRIVERPOSTSYNC_TASK_READY" = "1" ] && break
done

# Existing golden images keep working until the canonical bootstrap has been
# installed and captured. Legacy names are read-only compatibility inputs.
if [ "$DRIVERPOSTSYNC_TASK_READY" != "1" ]; then
    for WINDOWS_DIR in Windows WINDOWS windows; do
        TASK_CANDIDATE="$DRIVERPOSTSYNC_WINDOWS_ROOT/$WINDOWS_DIR/System32/Tasks/LINBO-Patchless-Driver-Install"
        [ -f "$TASK_CANDIDATE" ] || continue
        for PROGRAMDATA_DIR in ProgramData PROGRAMDATA programdata; do
            MARKER_CANDIDATE="$DRIVERPOSTSYNC_WINDOWS_ROOT/$PROGRAMDATA_DIR/LINBO-Patchless/startup-task-ready"
            if [ -f "$MARKER_CANDIDATE" ] &&
               [ "$(cat "$MARKER_CANDIDATE" 2>/dev/null)" = "LINBO-Patchless SYSTEM startup task v1" ]; then
                DRIVERPOSTSYNC_TASK_FILE="$TASK_CANDIDATE"
                DRIVERPOSTSYNC_TASK_MARKER="$MARKER_CANDIDATE"
                DRIVERPOSTSYNC_TASK_READY=1
                break
            fi
        done
        [ "$DRIVERPOSTSYNC_TASK_READY" = "1" ] && break
    done
fi

if [ "$DRIVERPOSTSYNC_BATCH_READY" = "1" ] && [ "$DRIVERPOSTSYNC_TASK_READY" = "1" ]; then
    cat > "$DRIVERPOSTSYNC_REGISTRY_FILE" << 'REG'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]
"LinboDriverInstall"=-
"!LinboDriverInstall"=-
REG
    DRIVERPOSTSYNC_REGISTRY_ACTION="task"
    echo "SYSTEM startup task detected; legacy RunOnce values will be removed." | tee -a "$DRIVERPOSTSYNC_LOG"
elif [ "$DRIVERPOSTSYNC_BATCH_READY" = "1" ]; then
    cat > "$DRIVERPOSTSYNC_REGISTRY_FILE" << 'REG'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]
"LinboDriverInstall"=-
"!LinboDriverInstall"="cmd.exe /d /s /c C:\\Drivers\\LINBO\\pnputil-install.cmd"
REG
    DRIVERPOSTSYNC_REGISTRY_ACTION="fallback"
    echo "Warning: SYSTEM startup task missing; !LinboDriverInstall fallback requires an administrator logon." | tee -a "$DRIVERPOSTSYNC_LOG"
else
    cat > "$DRIVERPOSTSYNC_REGISTRY_FILE" << 'REG'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]
"LinboDriverInstall"=-
"!LinboDriverInstall"=-
REG
    DRIVERPOSTSYNC_REGISTRY_ACTION="remove"
    if [ "$DRIVERPOSTSYNC_INSTALL_READY" != "1" ]; then
        echo "Driver payload unavailable — clearing RunOnce fallbacks." | tee -a "$DRIVERPOSTSYNC_LOG"
    else
        echo "No INF files found — clearing RunOnce fallbacks." | tee -a "$DRIVERPOSTSYNC_LOG"
    fi
fi

linbo_patch_registry "$DRIVERPOSTSYNC_REGISTRY_FILE" > "$DRIVERPOSTSYNC_REGISTRY_LOG" 2>&1
DRIVERPOSTSYNC_REGISTRY_RC=$?
tee -a "$DRIVERPOSTSYNC_LOG" < "$DRIVERPOSTSYNC_REGISTRY_LOG"
if [ "$DRIVERPOSTSYNC_REGISTRY_RC" = "0" ]; then
    case "$DRIVERPOSTSYNC_REGISTRY_ACTION" in
        task) echo "Driver auto-install: $INF_COUNT INF files, persistent SYSTEM startup task ready" | tee -a "$DRIVERPOSTSYNC_LOG" ;;
        fallback) echo "RunOnce fallback registered for $INF_COUNT INF files; administrator logon required" | tee -a "$DRIVERPOSTSYNC_LOG" ;;
        remove) echo "Removed stale LinboDriverInstall RunOnce values" | tee -a "$DRIVERPOSTSYNC_LOG" ;;
    esac
else
    echo "Warning: linbo_patch_registry returned $DRIVERPOSTSYNC_REGISTRY_RC while requesting RunOnce $DRIVERPOSTSYNC_REGISTRY_ACTION; some LINBO 7.4 releases do not provide a reliable exit status, inspect helper output." | tee -a "$DRIVERPOSTSYNC_LOG"
fi
rm -f "$DRIVERPOSTSYNC_REGISTRY_FILE" "$DRIVERPOSTSYNC_REGISTRY_LOG"

cp "$DRIVERPOSTSYNC_LOG" "/cache/linbo-driverpostsync.log" 2>/dev/null
return "$DRIVERPOSTSYNC_RC"
"""

_TOMBSTONE_TEMPLATE = r"""#!/bin/sh
# Managed-By: linuxmusterTools.linbo.driver_hooks v1
# =============================================================================
# Auto-generated driverpostsync tombstone for image: @@IMAGE@@
# Generated by linuxmuster.net LINBO — DO NOT EDIT MANUALLY
# =============================================================================

DRIVERPOSTSYNC_IMAGE="@@IMAGE@@"
DRIVERPOSTSYNC_RC=0
DRIVERPOSTSYNC_LOG="/tmp/linbo-driverpostsync.log"
DRIVERPOSTSYNC_CACHE="/cache/linbo-driverprofiles/$DRIVERPOSTSYNC_IMAGE"
DRIVERPOSTSYNC_WINDOWS_ROOT="/mnt"
DRIVERPOSTSYNC_TARGET="/mnt/Drivers/LINBO"
DRIVERPOSTSYNC_REGISTRY_FILE="/tmp/linbo-driver-install-remove.$$.reg"
DRIVERPOSTSYNC_REGISTRY_LOG="/tmp/linbo-driverpostsync-registry.$$"

echo "=== LINBO Driver Postsync tombstone for $DRIVERPOSTSYNC_IMAGE $(date) ===" > "$DRIVERPOSTSYNC_LOG"
if [ ! -d "$DRIVERPOSTSYNC_WINDOWS_ROOT/Windows/System32/config" ] &&
   [ ! -d "$DRIVERPOSTSYNC_WINDOWS_ROOT/WINDOWS/System32/config" ] &&
   [ ! -d "$DRIVERPOSTSYNC_WINDOWS_ROOT/windows/System32/config" ]; then
    echo "Non-Windows target detected; cleanup tombstone skipped." | tee -a "$DRIVERPOSTSYNC_LOG"
    cp "$DRIVERPOSTSYNC_LOG" "/cache/linbo-driverpostsync.log" 2>/dev/null
    return 0
fi

echo "No driver profiles assigned; clearing managed target and image cache." | tee -a "$DRIVERPOSTSYNC_LOG"
if ! rm -rf "$DRIVERPOSTSYNC_TARGET" "$DRIVERPOSTSYNC_CACHE"; then
    echo "Failed to clear managed target or image cache." | tee -a "$DRIVERPOSTSYNC_LOG"
    DRIVERPOSTSYNC_RC=1
fi

cat > "$DRIVERPOSTSYNC_REGISTRY_FILE" << 'REG'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]
"LinboDriverInstall"=-
"!LinboDriverInstall"=-
REG
linbo_patch_registry "$DRIVERPOSTSYNC_REGISTRY_FILE" > "$DRIVERPOSTSYNC_REGISTRY_LOG" 2>&1
DRIVERPOSTSYNC_REGISTRY_RC=$?
tee -a "$DRIVERPOSTSYNC_LOG" < "$DRIVERPOSTSYNC_REGISTRY_LOG"
if [ "$DRIVERPOSTSYNC_REGISTRY_RC" = "0" ]; then
    echo "Removed stale LinboDriverInstall RunOnce values." | tee -a "$DRIVERPOSTSYNC_LOG"
else
    echo "Warning: linbo_patch_registry returned $DRIVERPOSTSYNC_REGISTRY_RC while removing RunOnce; some LINBO 7.4 releases do not provide a reliable exit status, inspect helper output." | tee -a "$DRIVERPOSTSYNC_LOG"
fi
rm -f "$DRIVERPOSTSYNC_REGISTRY_FILE" "$DRIVERPOSTSYNC_REGISTRY_LOG"

cp "$DRIVERPOSTSYNC_LOG" "/cache/linbo-driverpostsync.log" 2>/dev/null
return "$DRIVERPOSTSYNC_RC"
"""


__all__ = [
    "DEFAULT_DRIVERS_ROOT",
    "DEFAULT_IMAGES_ROOT",
    "MANAGED_HEADER",
    "DriverAssignmentScanError",
    "DriverHookError",
    "DriverImageAssignedError",
    "DriverHookOwnershipError",
    "DriverHookTransactionError",
    "LinboDriverHookManager",
    "validate_profile_name",
    "validate_image_name",
    "render_driverpostsync",
]
