"""Manage hardware-specific LINBO driver profile and image metadata.

``LinboDriverManager`` owns profile directories and their image-independent
``match.conf``. ``WindowsDrivers`` is bound to one ``LinboImageGroup`` and
owns its ``image.conf`` assignments and ``.driverpostsync`` dispatcher.
Both profile configuration files remain below ``/srv/linbo/drivers``; the
dispatcher is published in the bound image group's directory.
Hardware inventory, archive extraction and payload validation remain separate.
"""

import fcntl
import logging
import os
import re
import shutil
import stat
import tempfile
import uuid
from contextlib import contextmanager
from pathlib import Path

from configobj import ConfigObjError

from ..common.checks import NameChecker
from ..lmnfile import LMNFile


__all__ = [
    "DriverProfileExistsError",
    "LinboDriverManager",
]


logger = logging.getLogger(__name__)
name_checker = NameChecker()

DEFAULT_DRIVERS_BASE = Path(
    os.environ.get("DRIVERS_BASE", "/srv/linbo/drivers")
)
MATCH_CONF_FILENAME = "match.conf"
IMAGE_CONF_FILENAME = "image.conf"
MAX_MATCH_VALUE_LENGTH = 512
MUTATION_LOCK_FILENAME = ".driver-profiles.lock"
DRIVERPOSTSYNC_MODE = 0o664
DRIVERPOSTSYNC_MANAGED_HEADER = (
    "# Managed-By: linuxmusterTools.linbo.driver_hooks v1"
)
DRIVERPOSTSYNC_LEGACY_HEADER = (
    "# Generated by LINBO Patchless — DO NOT EDIT MANUALLY"
)

_MATCH_VALUE = re.compile(r"^[a-zA-Z0-9 .,()/_+-]+$")
_WINDOWS_RESERVED_STEMS = frozenset(
    {
        "aux",
        "con",
        "nul",
        "prn",
        *(f"com{number}" for number in range(1, 10)),
        *(f"lpt{number}" for number in range(1, 10)),
    }
)


class DriverProfileExistsError(FileExistsError):
    """Raised when a new profile would replace an existing path."""

    def __init__(self, profile):
        super().__init__(f"Driver profile already exists: {profile}")
        self.profile = profile


def _validated_profile_name(name):
    """Return a profile name compatible with LMN paths and Windows."""

    if not isinstance(name, str):
        raise ValueError("Profile name must be a string.")

    normalized = name.strip()
    if (
        not name_checker.check_linbo_image_name(normalized)
        or not normalized[0].isalnum()
        or len(normalized) > 100
        or normalized.endswith(".")
    ):
        raise ValueError(
            "Profile name must start with an alphanumeric character, contain "
            "only [a-zA-Z0-9._-], and be at most 100 characters long."
        )

    windows_stem = normalized.partition(".")[0].casefold()
    if (
        windows_stem in _WINDOWS_RESERVED_STEMS
        or normalized.casefold() == "pnputil-install.cmd"
    ):
        raise ValueError(f"Windows-reserved profile name: {normalized}")
    return normalized


def _validated_driver_image(image):
    """Return an image basename supported by the LINBO driver runtime."""

    if (
        not name_checker.check_linbo_image_name(image)
        or "." in image
        or len(image) > 100
    ):
        raise ValueError(
            "Driver image names must contain only [A-Za-z0-9_-] and be "
            "at most 100 characters long."
        )
    return image


def _validated_match(vendor, product):
    """Validate one canonical DMI vendor/product pair."""

    result = {}
    for field, value in (("vendor", vendor), ("product", product)):
        if not isinstance(value, str):
            raise ValueError(f"{field} must be a string.")
        normalized = value.strip()
        if not normalized:
            raise ValueError(f"{field} must not be empty.")
        if len(normalized) > MAX_MATCH_VALUE_LENGTH:
            raise ValueError(
                f"{field} is too long (max {MAX_MATCH_VALUE_LENGTH} characters)."
            )
        if normalized != "*" and not _MATCH_VALUE.fullmatch(normalized):
            raise ValueError(f"{field} contains unsupported characters.")
        result[field] = normalized
    return result


@contextmanager
def _mutation_lock(base):
    """Serialize the short profile metadata mutations between API workers."""

    lock_path = Path(base) / MUTATION_LOCK_FILENAME
    flags = os.O_CREAT | os.O_RDWR
    if hasattr(os, "O_CLOEXEC"):
        flags |= os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW

    lock_fd = os.open(str(lock_path), flags, 0o600)
    locked = False
    try:
        metadata = os.fstat(lock_fd)
        if not stat.S_ISREG(metadata.st_mode):
            raise ValueError(f"Driver profile lock is not a regular file: {lock_path}")
        os.fchmod(lock_fd, 0o600)
        fcntl.flock(lock_fd, fcntl.LOCK_EX)
        locked = True
        yield
    finally:
        if locked:
            fcntl.flock(lock_fd, fcntl.LOCK_UN)
        os.close(lock_fd)


class LinboDriverManager:
    """Create, read, update and delete LINBO driver profile metadata."""

    def __init__(self, drivers_base=None):
        self.base = (
            Path(drivers_base)
            if drivers_base is not None
            else DEFAULT_DRIVERS_BASE
        )

    def _ensure_base_directory(self):
        if os.path.lexists(self.base):
            mode = self.base.lstat().st_mode
            if stat.S_ISLNK(mode) or not stat.S_ISDIR(mode):
                raise ValueError(
                    f"Driver profile base is not a real directory: {self.base}"
                )
            return

        self.base.mkdir(parents=True, mode=0o755, exist_ok=True)
        mode = self.base.lstat().st_mode
        if stat.S_ISLNK(mode) or not stat.S_ISDIR(mode):
            raise ValueError(
                f"Driver profile base is not a real directory: {self.base}"
            )

    @contextmanager
    def _mutation(self):
        """Serialize one driver profile metadata mutation."""

        self._ensure_base_directory()
        with _mutation_lock(self.base):
            yield

    @staticmethod
    def _write_profile_conf(path, section, values):
        """Write one canonical profile configuration through LMNFile."""

        is_new = not os.path.lexists(path)
        with LMNFile(
            str(path),
            "w",
            convert_values=False,
        ) as profile_file:
            data = profile_file.read()
            data.clear()
            data[section] = values
            profile_file.write(data)
        if is_new:
            path.chmod(0o644)

    def list_profiles(self, *, strict=False):
        """Return every complete, valid profile sorted by name.

        Raise the first profile error instead of skipping it when ``strict``
        is true.
        """

        if not os.path.lexists(self.base):
            return []
        self._ensure_base_directory()

        profiles = []
        for candidate in sorted(self.base.iterdir(), key=lambda path: path.name):
            if candidate.name.startswith("."):
                continue
            try:
                profile = self.get_profile(candidate.name)
            except (OSError, ValueError, ConfigObjError) as error:
                if strict:
                    raise
                logger.warning(
                    "Ignoring invalid driver profile %s: %s",
                    candidate.name,
                    error,
                )
                continue
            if profile is not None:
                profiles.append(profile)
        return profiles

    def get_profile(self, name):
        """Return one valid profile or ``None`` when its path is absent."""

        safe_name = _validated_profile_name(name)
        if not os.path.lexists(self.base):
            return None
        self._ensure_base_directory()
        profile_path = self.base / safe_name
        try:
            profile_mode = profile_path.lstat().st_mode
        except FileNotFoundError:
            return None
        if stat.S_ISLNK(profile_mode) or not stat.S_ISDIR(profile_mode):
            raise ValueError(
                f"Driver profile path is not a real directory: {safe_name}"
            )

        match_path = profile_path / MATCH_CONF_FILENAME
        try:
            match_mode = match_path.lstat().st_mode
        except FileNotFoundError as error:
            raise ValueError(
                f"Driver profile has no {MATCH_CONF_FILENAME}: {safe_name}"
            ) from error
        if stat.S_ISLNK(match_mode) or not stat.S_ISREG(match_mode):
            raise ValueError(
                f"Driver profile {MATCH_CONF_FILENAME} is not a regular file: "
                f"{safe_name}"
            )

        try:
            with LMNFile(
                str(match_path),
                "r",
                convert_values=False,
            ) as match_file:
                data = match_file.read()
        except ConfigObjError as error:
            raise ValueError(
                f"Invalid {MATCH_CONF_FILENAME} for driver profile {safe_name}: "
                f"{error}"
            ) from error

        if set(data.keys()) != {"match"}:
            raise ValueError(
                f"{MATCH_CONF_FILENAME} must contain exactly one [match] section."
            )
        if data.inline_comments.get("match"):
            raise ValueError(
                f"{MATCH_CONF_FILENAME} must not contain inline comments."
            )
        section = data["match"]
        if (
            not isinstance(section, dict)
            or set(section.keys()) != {"vendor", "product"}
        ):
            raise ValueError(
                "[match] must contain exactly one vendor and one product."
            )
        if any(section.inline_comments.get(key) for key in section):
            raise ValueError(
                f"{MATCH_CONF_FILENAME} must not contain inline comments."
            )
        match = _validated_match(section["vendor"], section["product"])

        return {
            "name": safe_name,
            "path": str(profile_path),
            "matchConf": match,
        }

    def create_profile(self, name, vendor, product):
        """Create a profile without replacing any existing path."""

        safe_name = _validated_profile_name(name)
        match = _validated_match(vendor, product)
        with self._mutation():
            with os.scandir(self.base) as entries:
                collision = any(
                    entry.name.casefold() == safe_name.casefold()
                    or entry.name.casefold().startswith(
                        f".{safe_name.casefold()}.deleting-"
                    )
                    for entry in entries
                )
            if collision:
                raise DriverProfileExistsError(safe_name)

            profile_path = self.base / safe_name
            try:
                profile_path.mkdir(mode=0o755)
            except FileExistsError as error:
                raise DriverProfileExistsError(safe_name) from error

            try:
                self._write_profile_conf(
                    profile_path / MATCH_CONF_FILENAME,
                    "match",
                    match,
                )
            except Exception:
                try:
                    profile_path.rmdir()
                except OSError:
                    pass
                raise

        return self.get_profile(safe_name)

    def update_match(self, name, vendor, product):
        """Replace only ``match.conf`` and preserve all driver payload files."""

        match = _validated_match(vendor, product)
        if not os.path.lexists(self.base):
            raise FileNotFoundError(f"Driver profile not found: {name}")
        with self._mutation():
            profile = self.get_profile(name)
            if profile is None:
                raise FileNotFoundError(f"Driver profile not found: {name}")

            self._write_profile_conf(
                Path(profile["path"]) / MATCH_CONF_FILENAME,
                "match",
                match,
            )
        return self.get_profile(profile["name"])

    def delete_profile(self, name):
        """Delete a valid managed profile and return whether it existed."""

        if not os.path.lexists(self.base):
            return False
        with self._mutation():
            profile = self.get_profile(name)
            if profile is None:
                return False
            profile_path = Path(profile["path"])
            if os.path.lexists(profile_path / IMAGE_CONF_FILENAME):
                raise ValueError(
                    f"Driver profile {profile['name']} is assigned; "
                    "unassign it before deleting."
                )
            quarantine = self.base / (
                f".{profile['name']}.deleting-{uuid.uuid4().hex}"
            )
            profile_path.rename(quarantine)

        try:
            shutil.rmtree(quarantine)
        except Exception:
            with self._mutation():
                if not os.path.lexists(profile_path) and os.path.lexists(quarantine):
                    quarantine.rename(profile_path)
            raise
        return True


class WindowsDrivers:
    """Manage the Windows driver metadata for one LINBO image group."""

    def __init__(self, image_group, driver_manager=None):
        self.image_group = image_group
        self.driver_manager = (
            driver_manager
            if driver_manager is not None
            else LinboDriverManager()
        )

    @staticmethod
    def validate_image(image):
        """Return an image basename supported by the driver runtime."""

        return _validated_driver_image(image)

    @staticmethod
    def _read_profile_assignment(profile):
        """Read one already validated profile's optional image assignment."""

        path = Path(profile["path"]) / IMAGE_CONF_FILENAME
        try:
            metadata = path.lstat()
        except FileNotFoundError:
            return None
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise ValueError(
                f"image.conf is not a regular file: {profile['name']}"
            )

        try:
            with LMNFile(str(path), "r", convert_values=False) as image_file:
                data = image_file.read()
        except ConfigObjError as error:
            raise ValueError(
                f"Invalid image.conf for driver profile {profile['name']}: "
                f"{error}"
            ) from error

        if set(data.keys()) != {"image"} or data.inline_comments.get("image"):
            raise ValueError(
                "image.conf must contain one canonical [image] section or "
                "one legacy image value."
            )

        section = data["image"]
        if isinstance(section, str):
            # Read compatibility for the standalone/.deb format.
            return _validated_driver_image(section)

        if not isinstance(section, dict) or set(section.keys()) != {"name"}:
            raise ValueError("[image] must contain exactly one name.")
        if section.inline_comments.get("name"):
            raise ValueError("image.conf must not contain inline comments.")
        return _validated_driver_image(section["name"])

    @classmethod
    def get_profile_image(cls, driver_manager, profile_name):
        """Return one profile's image assignment, if present."""

        profile = driver_manager.get_profile(profile_name)
        if profile is None:
            raise FileNotFoundError(
                f"Driver profile not found: {profile_name}"
            )
        return cls._read_profile_assignment(profile)

    def get_profiles(self):
        """Return this image's assigned profiles in deterministic order."""

        image = _validated_driver_image(self.image_group.name)
        profiles = []
        known_names = {}
        for profile in self.driver_manager.list_profiles(strict=True):
            name = profile["name"]
            normalized = name.casefold()
            previous = known_names.get(normalized)
            if previous is not None and previous != name:
                raise ValueError(
                    "Driver profile names differ only by case: "
                    f"{previous}, {name}"
                )
            known_names[normalized] = name
            if self._read_profile_assignment(profile) == image:
                profiles.append(name)
        return sorted(profiles, key=lambda value: (value.casefold(), value))

    def render_driverpostsync(self):
        """Render this image's thin static-runtime dispatcher."""

        image = _validated_driver_image(self.image_group.name)
        profiles = self.get_profiles()
        profile_comment = ", ".join(profiles) or "(none)"
        arguments = "".join(f' "{profile}"' for profile in profiles)
        return (
            "#!/bin/sh\n"
            f"{DRIVERPOSTSYNC_MANAGED_HEADER}\n"
            f"# Image: {image}\n"
            f"# Profiles: {profile_comment}\n\n"
            "if ! command -v linbo_driverpostsync >/dev/null 2>&1; then\n"
            '    echo "LINBO driver runtime is missing." >&2\n'
            "    return 1\n"
            "fi\n\n"
            f'linbo_driverpostsync "{image}"{arguments}\n'
            "return $?\n"
        )

    @staticmethod
    def _validate_driverpostsync_target(path):
        """Return existing hook metadata after validating its ownership."""

        image_directory = path.parent
        directory_metadata = image_directory.lstat()
        if not stat.S_ISDIR(directory_metadata.st_mode):
            raise ValueError(
                f"LINBO image path is not a real directory: {image_directory}"
            )

        target_metadata = None
        try:
            target_metadata = path.lstat()
        except FileNotFoundError:
            pass
        else:
            if not stat.S_ISREG(target_metadata.st_mode):
                raise ValueError(
                    f"driverpostsync hook is not a regular file: {path}"
                )

            try:
                with path.open("r", encoding="utf-8") as hook:
                    header = [
                        hook.readline(4097).rstrip("\r\n")
                        for _ in range(10)
                    ]
            except UnicodeError as error:
                raise PermissionError(
                    f"Refusing to overwrite unmanaged driverpostsync hook: {path}"
                ) from error
            legacy_image_headers = {
                f"# Auto-generated driverpostsync script for image: {path.stem}",
                f"# Auto-generated driverpostsync tombstone for image: {path.stem}",
            }
            is_managed = header[:2] == [
                "#!/bin/sh",
                DRIVERPOSTSYNC_MANAGED_HEADER,
            ]
            is_legacy = (
                header[0] == "#!/bin/sh"
                and DRIVERPOSTSYNC_LEGACY_HEADER in header
                and not legacy_image_headers.isdisjoint(header)
            )
            if not is_managed and not is_legacy:
                raise PermissionError(
                    f"Refusing to overwrite unmanaged driverpostsync hook: {path}"
                )
        return target_metadata

    @classmethod
    def _write_driverpostsync(cls, path, content):
        """Atomically replace one owned raw driverpostsync hook."""

        image_directory = path.parent
        target_metadata = cls._validate_driverpostsync_target(path)

        temporary = None
        try:
            fd, temporary = tempfile.mkstemp(
                prefix=f".{path.name}.",
                suffix=".tmp",
                dir=str(image_directory),
            )
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as hook:
                hook.write(content)
                hook.flush()
                if target_metadata is not None:
                    temporary_metadata = os.fstat(hook.fileno())
                    if (
                        temporary_metadata.st_uid != target_metadata.st_uid
                        or temporary_metadata.st_gid != target_metadata.st_gid
                    ):
                        os.fchown(
                            hook.fileno(),
                            target_metadata.st_uid,
                            target_metadata.st_gid,
                        )
                os.fchmod(hook.fileno(), DRIVERPOSTSYNC_MODE)
                os.fsync(hook.fileno())
            os.replace(temporary, path)
            temporary = None
            directory_fd = os.open(str(image_directory), os.O_RDONLY)
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
        finally:
            if temporary is not None:
                try:
                    os.unlink(temporary)
                except FileNotFoundError:
                    pass

    def _driverpostsync_path(self):
        """Return this image group's driverpostsync hook path."""

        return (
            Path(self.image_group.path)
            / f"{self.image_group.name}.driverpostsync"
        )

    def _preflight_driverpostsync(self):
        """Validate this image's configuration and existing hook target."""

        self.render_driverpostsync()
        self._validate_driverpostsync_target(self._driverpostsync_path())

    def _regenerate_driverpostsync(self):
        """Render and publish this image's managed driverpostsync hook."""

        content = self.render_driverpostsync()
        path = self._driverpostsync_path()
        self._write_driverpostsync(path, content)
        return path

    def publish_driverpostsync(self):
        """Publish this image's dispatcher under the profile mutation lock."""

        with self.driver_manager._mutation():
            return str(self._regenerate_driverpostsync())

    @staticmethod
    def _write_profile_assignment(driver_manager, profile, image):
        """Set one assignment while the caller holds the mutation lock."""

        path = Path(profile["path"]) / IMAGE_CONF_FILENAME
        if image is None:
            path.unlink(missing_ok=True)
            return
        driver_manager._write_profile_conf(
            path,
            "image",
            {"name": _validated_driver_image(image)},
        )

    @classmethod
    def _apply_assignment(
        cls,
        driver_manager,
        profile,
        previous_image,
        image,
        affected,
    ):
        """Change one assignment and publish every affected dispatcher."""

        if previous_image is None and image is None:
            return

        assignment = Path(profile["path"]) / IMAGE_CONF_FILENAME
        previous_metadata = (
            assignment.lstat() if previous_image is not None else None
        )
        for windows_drivers in affected:
            windows_drivers._preflight_driverpostsync()

        attempted = []
        try:
            cls._write_profile_assignment(driver_manager, profile, image)
            for windows_drivers in affected:
                attempted.append(windows_drivers)
                windows_drivers._regenerate_driverpostsync()
        except Exception as error:
            rollback_errors = []
            try:
                cls._write_profile_assignment(
                    driver_manager,
                    profile,
                    previous_image,
                )
                if previous_metadata is not None:
                    restored = assignment.stat()
                    if (
                        restored.st_uid != previous_metadata.st_uid
                        or restored.st_gid != previous_metadata.st_gid
                    ):
                        os.chown(
                            assignment,
                            previous_metadata.st_uid,
                            previous_metadata.st_gid,
                        )
                    assignment.chmod(stat.S_IMODE(previous_metadata.st_mode))
            except Exception as rollback_error:
                rollback_errors.append(rollback_error)
            for windows_drivers in attempted:
                try:
                    windows_drivers._regenerate_driverpostsync()
                except Exception as rollback_error:
                    rollback_errors.append(rollback_error)
            if rollback_errors:
                details = "; ".join(str(item) for item in rollback_errors)
                raise RuntimeError(
                    "Driver assignment publication failed for "
                    f"{profile['name']} ({error}); rollback was incomplete: "
                    f"{details}"
                ) from rollback_errors[0]
            raise

    def _change_own_assignment(self, profile_name, assigned):
        """Change only this image group's assignment under one lock."""

        if not os.path.lexists(self.driver_manager.base):
            raise FileNotFoundError(
                f"Driver profile not found: {profile_name}"
            )
        with self.driver_manager._mutation():
            profile = self.driver_manager.get_profile(profile_name)
            if profile is None:
                raise FileNotFoundError(
                    f"Driver profile not found: {profile_name}"
                )
            image = _validated_driver_image(self.image_group.name)
            previous_image = self._read_profile_assignment(profile)
            if previous_image not in (None, image):
                if assigned:
                    raise ValueError(
                        f"Driver profile {profile['name']} is assigned to "
                        f"{previous_image}; use LinboImageManager to move it."
                    )
                raise ValueError(
                    f"Driver profile {profile['name']} is assigned to "
                    f"{previous_image}, not {image}."
                )
            target_image = image if assigned else None
            affected = [self] if assigned or previous_image is not None else []
            self._apply_assignment(
                self.driver_manager,
                profile,
                previous_image,
                target_image,
                affected,
            )
        return profile, target_image

    def assign_profile(self, profile_name):
        """Assign a profile to this image and publish its dispatcher."""

        profile, image = self._change_own_assignment(profile_name, True)
        return {"profile": profile["name"], "image": image}

    def unassign_profile(self, profile_name):
        """Remove this image's profile assignment and publish its hook."""

        profile, _ = self._change_own_assignment(profile_name, False)
        return {"profile": profile["name"], "image": None}
