#! /usr/bin/env python3

import argparse
import sys

from linuxmusterTools.common import lprint
from linuxmusterTools.ldapconnector import LMNStudent


parser = argparse.ArgumentParser(
                    prog='lmntools-student',
                    description='Handle attributes of students')

parser.add_argument('-u', '--user', help="Cn of the student to handle")
parser.add_argument('--get-parents', help="Get the parents", action="store_true")
parser.add_argument('--add-parents', help="Comma separated list of the cn of the parents to assign")
parser.add_argument('--remove-parents', help="Comma separated list of the cn of the parents to remove")

args = parser.parse_args()

if args.user is not None:

    if not args.add_parents and not args.remove_parents and not args.get_parents:
        parser.print_help()
        sys.exit(0)

    try:
        student = LMNStudent(args.user)

        if args.add_parents:
            for parent in args.add_parents.split(','):
                student.add_parent(parent)

        if args.remove_parents:
            for parent in args.remove_parents.split(','):
                student.remove_parent(parent)

        if args.get_parents:
            if student.parents:
                for parent in student.parents:
                    lprint.info(f"{parent['cn']};{parent['displayName']}")
            else:
                lprint.info('No parent found!')

    except Exception as e:
        print(e)
        sys.exit(1)

else:
    parser.print_help()
