#!/bin/bash
#
# postinst script for linuxmuster-tools7
# GPL v3
#

set -e

# Hide root warning for pip
export PIP_ROOT_USER_ACTION=ignore
export PIP_BREAK_SYSTEM_PACKAGES=1

msg()
{
    message=$1
    echo
    # Bold and orange font for linuxmuster.net
    echo -e "\e[1m\e[38;5;214m$message\e[39m\e[0m"
    echo
}


create_linuxmuster_venv()
{
    msg "Setting up virtual env in /opt"
    /usr/bin/python3 -m venv /opt/linuxmuster --system-site-packages
}

migrate_to_venv()
{
    # Checking if the linuxmuster's venv  is already installed
    if [ -f /opt/linuxmuster/bin/activate ] ; then
      return
    fi

    create_linuxmuster_venv
}


case "$1" in
    install|configure)
        msg "Install Python requirements"

        migrate_to_venv
        . /opt/linuxmuster/bin/activate
        
        PYTHON3=/opt/linuxmuster/bin/python3
        
        $PYTHON3 -m pip install -r /usr/lib/python3/dist-packages/linuxmusterTools/requirements.txt

        msg "Checking post-hooks directories"
        mkdir -p /etc/linuxmuster/tools/hooks/group-manager
        chown root:root /etc/linuxmuster/tools/hooks/group-manager -R
        chmod 600 /etc/linuxmuster/tools/hooks/group-manager -R

        msg "Checking students group in LDAP"
        $PYTHON3 /usr/lib/python3/dist-packages/linuxmusterTools/install-scripts/create_students_groups.py

    ;;

    *)
    ;;

esac

exit 0
