#!/bin/bash
#
# postinst script for linuxmuster-tools8
# GPL v3
#

set -e

msg()
{
    message=$1
    echo
    # Bold and orange font for linuxmuster.net
    echo -e "\e[1m\e[38;5;214m$message\e[39m\e[0m"
    echo
}

case "$1" in
    install|configure)
        msg "Install Python requirements"
        /usr/bin/python3 -m pip install -r /usr/lib/python3/dist-packages/linuxmusterTools/requirements.txt

        msg "Checking post-hooks directories"
        mkdir -p /etc/linuxmuster/tools/hooks/group-manager
        chown root:root /etc/linuxmuster/tools/hooks/group-manager -R
        chmod 600 /etc/linuxmuster/tools/hooks/group-manager -R

    ;;

    *)
    ;;

esac

exit 0
